"use client"

import { useState } from 'react';
import { ThemeProviders } from './themeProviders'
import SquaresGrid from './components/SquaresGrid';
import ScrollContext from './context/ScrollContext';
import Header from './components/Header'
import Footer from './components/Footer'
import './styles/globals.scss'

import { IBM_Plex_Sans } from 'next/font/google'
import { Poppins } from 'next/font/google'


const ibmPlexSans = IBM_Plex_Sans({ 
    weight: ['300', '400', '500', '600', '700'],
    styles: ['normal', 'italic'],
    subsets: ['latin'] 
})

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700'],
    styles: ['normal', 'italic'],
    subsets: ['latin']
})



// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function Layout({ children }) {
    const [sectionInView, setSectionInView] = useState("");

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={poppins.className}>
                <ThemeProviders>
                    <ScrollContext.Provider value={{ sectionInView, setSectionInView }}>
                        <div className='page-container'>
                            <Header />
                            {children}
                            <Footer />
                        </div>
                    </ScrollContext.Provider>
                </ThemeProviders>
            </body>
        </html>
    )
}
